# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNFabricExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFabricExample

	pod 'Fabric'
	pod 'Crashlytics'
	# pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
  target 'RNFabricExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNFabricExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNFabricExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFabricExample-tvOS

  #target 'RNFabricExample-tvOSTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

end
