# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '9.0'


target 'RNFabricExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFabricExample
  # shared_pods
  # pod 'React'
  pod 'Firebase/Core'
	pod 'Fabric'
  pod 'Crashlytics'
  pod 'React', :subspecs => [
    #  'RCTLog',
     'RCTAnimation',
     'RCTActionSheet',
     'RCTGeolocation',
     'RCTImage',
     'RCTLinkingIOS',
     'RCTNetwork',
     'RCTSettings',
     'RCTText',
     'RCTVibration',
     'RCTWebSocket'], :path => '../node_modules/react-native'

  pod 'yoga',
    path: '../node_modules/react-native/ReactCommon/yoga'
	# pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
  target 'RNFabricExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNFabricExampleTests' do
    inherit! :search_paths
    pod 'Fabric'
  pod 'Crashlytics'
  pod 'React', :subspecs => [
    #  'RCTLog',
     'RCTAnimation',
     'RCTActionSheet',
     'RCTGeolocation',
     'RCTImage',
     'RCTLinkingIOS',
     'RCTNetwork',
     'RCTSettings',
     'RCTText',
     'RCTVibration',
     'RCTWebSocket'], :path => '../node_modules/react-native'

  pod 'yoga',
    path: '../node_modules/react-native/ReactCommon/yoga'
    # Pods for testing
  end

end

target 'RNFabricExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFabricExample-tvOS

  #target 'RNFabricExample-tvOSTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

end
